### ISSUE TITLE
Travis CI upload issues

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/line_profiler-feedstock#6]
See this [build](https://travis-ci.org/conda-forge/line_profiler-feedstock/jobs/153992253#L589) for an example. We have triggered a fresh Travis CI build on `master` by pushing an empty commit. So please don't restart that log. Snippet shown below. Note that the build still passed even though it should have failed just like the CircleCI and AppVeyor upload issues. So there is something we need to fix here. As a result, we can confirm that we are seeing issue ( https://github.com/conda-forge/status/issues/4 ) with all CIs.

```
$ ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "./ci_support/upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "./ci_support/upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "./ci_support/upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/binstar_client/mixins/channels.py", line 29, in show_channel
    self._check_response(res, [200])
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/binstar_client/__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ('Not Found: Nothing matches the given URI ([GET] https://api.anaconda.org/channels/conda-forge/main -> 404)', 404)
```

cc @pelson

**Comment by jakirkham** [comment]
Uploaded the Python 3.5 package in this subsequent [build](https://travis-ci.org/conda-forge/line_profiler-feedstock/jobs/153997681#L591) and confirmed it is up. So no need to restart.

**Comment by jakirkham** [comment]
Raised this underlying no error issue upstream as issue ( https://github.com/conda-forge/conda-smithy/issues/267 ).
